"""Domain-split data layer. Import surface is unchanged: every symbol
previously on media_workspace.db is re-exported here."""

from ..schema import SCHEMA_VERSION
from .assets import (
    confirm_match,
    count_assets_for_annotation,
    get_duplicate_assets,
    get_registry,
    list_assets_for_annotation,
    list_assets_for_preview,
    list_catalog_roots,
    list_collage_sources,
    list_collages_using_asset,
    list_pending,
    list_repaint_history,
    load_raw_cache,
    load_raw_cache_index,
    load_raw_candidates,
    load_raw_candidates_by_camera,
    load_raw_candidates_by_camera_token,
    load_raw_candidates_by_capture_window,
    load_raw_enrichment_candidates,
    set_asset_rating,
    upsert_catalog_root,
    upsert_image_asset,
    upsert_preview_entry,
    upsert_raw_asset,
    upsert_registry,
    upsert_video_asset,
)
from .browse import (
    _browse_order_clause,
    _facet_clauses,
    browse_collection,
    get_facet_values,
    get_image_asset_detail,
    get_image_asset_detail_by_path,
    list_image_assets,
    list_version_siblings,
    locate_image_asset,
    search_facet_values,
)
from .collections import (
    _collection_id,
    add_collection_items,
    create_collection,
    delete_collection,
    list_collections,
    remove_collection_items,
    reorder_collections,
    update_collection,
)
from .core import RESOLVER_VERSION, _ensure_column, _file_id, _json, connect, init_db, set_catalog_path
from .jobs import (
    _UNSET,  # sentinel shared with update_job callers
    _decode_job_row,
    _job_id,
    create_job,
    get_job,
    get_latest_job,
    is_cancel_requested,
    is_pause_requested,
    list_active_jobs,
    list_jobs,
    request_job_cancel,
    request_job_pause,
    request_job_resume,
    update_job,
)
from .locations import (
    delete_asset_location,
    get_asset_location,
    list_map_points,
    set_manual_asset_location,
    upsert_ai_asset_location,
    upsert_asset_location_from_metadata,
)
from .maintenance import cleanup_orphan_image_assets, delete_image_asset_from_catalog, relink_asset, summary, verify_assets
from .people import (
    assign_face_to_group,
    assign_faces_to_group,
    get_asset_people,
    get_people_asset_index,
    get_person_group_detail,
    list_asset_faces,
    list_people_index_candidates,
    list_person_groups,
    list_similar_person_groups,
    merge_person_groups,
    rebuild_candidate_groups,
    remove_face_from_group,
    remove_faces_from_group,
    replace_asset_faces,
    set_person_group_cover,
    set_person_group_name,
    set_person_group_state,
    set_person_groups_state,
    upsert_face_model,
    upsert_people_asset_index,
)
from .resource_sets import (
    _link_id,
    _next_resource_sort_order,
    _resource_set_id,
    add_asset_to_resource_set,
    attach_asset_to_resource_set,
    create_resource_set,
    find_image_asset_ids_by_stem,
    get_resource_set,
    get_resource_set_for_asset,
    link_assets,
    list_image_assets_missing_resource_set,
    list_incorrectly_merged_resource_sets,
    list_singleton_primary_resource_sets,
    reassign_asset_to_resource_set,
    remove_raw_from_resource_sets,
    split_incorrectly_merged_sets,
    split_shared_asset_ids,
)
from .settings import delete_app_setting, get_app_setting, set_app_setting
